model_path: "models\\best_step4_batchs.pt"
dataset_path: "C:\\personal\\projects\\meal-table-detection\\data"
dataset_yaml_path: "C:\\personal\\projects\\meal-table-detection\\data\\data.yaml"
video_path: "videos\\4_rotated.mov"

desired_windows_width: 960
desired_windows_height: 640

min_confidence_level: 0.1 #Minimum confidence for a detection to be considered valid

plate_state_ioa_threshold: 0.8 #IoA (Intersection over Area) measures how much of one bounding box (usually the
#smaller one) is covered by another.

food_classes:
  - bone-in steak
  - borscht
  - caesar salad
  - cheese soup
  - flatbread
  - greek salad

plate_classes:
  - plate
  - wooden board

plate_state_classes:
  - plate bottom

other_classes:
  - shot
  - tea